name: Secure

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello"
  display-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files
        run: ls -al keys
